### ISSUE TITLE
Entrainer ce model

### ISSUE THREAD

**Issue by ValBaron10** [Simplon-devs/maldives-corals#2]
Which model is this issue for ? I need to know because there is the model for detecting the corals, nd the one to detect the structures.

**Comment by ValBaron10** [comment]
@JoaoAndre-RosaTeixeira @Mehdi-212 @Sophana63 @LakhbirSin finally who do this?

**Comment by ValBaron10** [comment]
It needs to be finished today if we want to be on time.

**Comment by LakhbirSin** [comment]
It was the model of Gaëtan but finally we are creating our own, so this issue is going to be closed.
